{
 "title": "Electrickery",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "High Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT high_price FROM octopus.electricity LIMIT 50 "
    }
   ]
  },
  {
   "title": "Daily Standing Charge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT standing_charge FROM octopus.electricity LIMIT 50 "
    }
   ]
  },
  {
   "title": "Elec Cost November",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.electricity WHERE end_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Elec Cost",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, start_time FROM octopus.electricity"
    }
   ]
  },
  {
   "title": "Low Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT low_price FROM octopus.electricity LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cost Oct 2023",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.electricity WHERE end_time BETWEEN '2023-10-01 00:00:00.000' AND '2023-10-31 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Standing Charge Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT standing_charge, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Car Charge Cost November",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT car_charge_cost, start_time FROM octopus.electricity WHERE end_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Total Car Charge Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT car_charge_cost, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Cost, Last Month",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, start_time FROM octopus.electricity WHERE end_time BETWEEN '2023-10-01 00:00:00.000' AND '2023-10-31 00:00:00.000' "
    }
   ]
  },
  {
   "title": "kWh Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT kwh, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "kWh Last Month",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT kwh, start_time FROM octopus.electricity "
    }
   ]
  }
 ]
}