{
 "title": "Electrickery",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Bump Charge Cost Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT bump_charge_cost, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Elec Cost November",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.electricity WHERE end_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Cost Oct 2023",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.electricity WHERE end_time BETWEEN '2023-10-01 00:00:00.000' AND '2023-10-31 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Elec Cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT SUM(cost) AS \"gas_cost\" FROM octopus.gas "
    },
    {
     "dataset": "octopus",
     "rawSql": "SELECT SUM(cost) FROM octopus.electricity "
    },
    { "expression": "$gas_cost+$elec_cost", "type": "math" },
    {
     "dataset": "octopus",
     "rawSql": "SELECT end_time FROM octopus.electricity WHERE end_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Car Charge Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT car_charge_cost, start_time, bump_charge_cost FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Nov Charge Costs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT car_charge_cost, start_time, bump_charge_cost FROM octopus.electricity WHERE end_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Gas Cost October",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.gas WHERE start_time BETWEEN '2023-10-01 00:00:00.000' AND '2023-10-31 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Gas Cost November",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, end_time FROM octopus.gas WHERE start_time BETWEEN '2023-11-01 00:00:00.000' AND '2023-11-30 00:00:00.000' "
    }
   ]
  },
  {
   "title": "Gas Cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, start_time FROM octopus.gas "
    }
   ]
  },
  {
   "title": "Low Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT low_price FROM octopus.electricity LIMIT 50 "
    }
   ]
  },
  {
   "title": "High Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT high_price FROM octopus.electricity LIMIT 50 "
    }
   ]
  },
  {
   "title": "Standing Charge Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT standing_charge, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Gas Standing Chrg Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT standing_charge, end_time FROM octopus.gas "
    }
   ]
  },
  {
   "title": "Cost, Last Month",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT cost, start_time FROM octopus.electricity WHERE end_time BETWEEN '2023-10-01 00:00:00.000' AND '2023-10-31 00:00:00.000' "
    }
   ]
  },
  {
   "title": "kWh Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT kwh, end_time, threshold, current_price FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "kWh Last Month",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT kwh, start_time FROM octopus.electricity "
    }
   ]
  },
  {
   "title": "Gas Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "octopus",
     "rawSql": "SELECT gas_kwh, start_time FROM octopus.gas "
    }
   ]
  }
 ]
}